title: Gregory V Santoro # your name (or website title) here
logo: "/images/Gregory_Profile_Photo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/gregory-santoro/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
