name: Dice Roll

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  roll-dice:
    runs-on: ubuntu-latest

    steps:
      - name: Set up R environment
        uses: r-lib/actions/setup-r@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install R packages
        run: |
          Rscript -e "install.packages('shiny')"

      - name: Execute R script
        run: Rscript your_script.R
